# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1906eaeae508f4625de506bbca68aa5ec65f6acb71548614acc20125cb2b597943854ae7b8350a43a7c92cde3a71973d68075d982598f43cd8b00bc004c2fe9

test:
  secret_key_base: c0a086e1a3d00a1e6345bf87c05d64be56ff7b814267e1d4cb8f4d6b504237ed7055665dd290e49aef57979da44b74da7bb8632618ca6ccf67848ca27dab308b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
